import { Icons } from 'react-native-nub';

module.exports = {
	"logo": require('./logo.png'),
	"splash": require('./marengo.jpg'),
	"menu": Icons['menu-dark'],
	"info": Icons['info-dark'],
	"refresh": Icons['refresh-dark'],
	"back": Icons['chevron-left-dark'],	

	"draw": require('./draw-from-cup.png'),
	"drawcup": require('./drawcup.png'),
	"resetcup": require('./reset-draw-cup.png'),
	
	"chit-blue.png": require('./chit-blue.png'),
	"chit-gray.png": require('./chit-gray.png'),
	"chit-red.png": require('./chit-red.png'),
	"chit-white.png": require('./chit-white.png'),

	"label-white.png": require('./chit-label-white.png'),
	"label-gray.png": require('./chit-label-gray.png'),
	
	"label-A.png": require('./chit-label-a.png'),
	"label-B.png": require('./chit-label-b.png'),
	"label-C.png": require('./chit-label-c.png'),
	"label-D.png": require('./chit-label-d.png'),
	"label-E.png": require('./chit-label-e.png'),
	"label-F.png": require('./chit-label-f.png'),
	"label-G.png": require('./chit-label-g.png'),
	"label-H.png": require('./chit-label-h.png'),
	"label-I.png": require('./chit-label-i.png'),
	"label-J.png": require('./chit-label-j.png'),
	"label-K.png": require('./chit-label-k.png'),
	"label-L.png": require('./chit-label-l.png'),
	"label-M.png": require('./chit-label-m.png'),
	"label-N.png": require('./chit-label-n.png'),
	"label-O.png": require('./chit-label-o.png'),
	"label-P.png": require('./chit-label-p.png'),
	"label-Q.png": require('./chit-label-q.png'),
	"label-R.png": require('./chit-label-r.png'),
	"label-S.png": require('./chit-label-s.png'),
	"label-T.png": require('./chit-label-t.png'),
	"label-U.png": require('./chit-label-u.png'),
	"label-V.png": require('./chit-label-v.png'),
	"label-W.png": require('./chit-label-w.png'),
	"label-X.png": require('./chit-label-x.png'),
	"label-Y.png": require('./chit-label-y.png'),
	"label-Z.png": require('./chit-label-z.png'),
	
	"label-II.png": require('./chit-label-II.png'),
	"label-III.png": require('./chit-label-III.png'),
	"label-IV.png": require('./chit-label-IV.png'),
	"label-VI.png": require('./chit-label-VI.png'),
	"label-VII.png": require('./chit-label-VII.png'),
	"label-VIII.png": require('./chit-label-VIII.png'),
	"label-IX.png": require('./chit-label-IX.png'),
	"label-XI.png": require('./chit-label-XI.png'),
	"label-XII.png": require('./chit-label-XII.png'),	
	
	//"French": require('./french_flag.jpg'),
	"French": require('./french.jpg'),
	"Austrian": require('./austrian_flag.png'),	

	"marengo": require("./marengo.jpg"),
	"antietam": require("./antietam.jpg"),
};
