import { Icons } from 'react-native-nub';

module.exports = {
	"logo": require('./logo.jpg'),
	"splash": require('./logo.jpg'),
	"menu": Icons['menu-light'],
	"info": Icons['info-light'],
	"refresh": Icons['refresh-light'],
	"back": Icons['chevron-left-light'],	

	"draw": require('./draw-from-cup.png'),
	"drawcup": require('./drawcup.png'),
	"resetcup": require('./reset-draw-cup.png'),
	
	"chit-blue": require('./chit-blue.png'),
	"chit-gray": require('./chit-gray.png'),
	"chit-red": require('./chit-red.png'),
	"chit-white": require('./chit-white.png'),

	"label-white": require('./chit-label-white.png'),
	"label-gray": require('./chit-label-gray.png'),
	
	"label-A": require('./chit-label-a.png'),
	"label-B": require('./chit-label-b.png'),
	"label-C": require('./chit-label-c.png'),
	"label-D": require('./chit-label-d.png'),
	"label-E": require('./chit-label-e.png'),
	"label-F": require('./chit-label-f.png'),
	"label-G": require('./chit-label-g.png'),
	"label-H": require('./chit-label-h.png'),
	"label-I": require('./chit-label-i.png'),
	"label-J": require('./chit-label-j.png'),
	"label-K": require('./chit-label-k.png'),
	"label-L": require('./chit-label-l.png'),
	"label-M": require('./chit-label-m.png'),
	"label-N": require('./chit-label-n.png'),
	"label-O": require('./chit-label-o.png'),
	"label-P": require('./chit-label-p.png'),
	"label-Q": require('./chit-label-q.png'),
	"label-R": require('./chit-label-r.png'),
	"label-S": require('./chit-label-s.png'),
	"label-T": require('./chit-label-t.png'),
	"label-U": require('./chit-label-u.png'),
	"label-V": require('./chit-label-v.png'),
	"label-W": require('./chit-label-w.png'),
	"label-X": require('./chit-label-x.png'),
	"label-Y": require('./chit-label-y.png'),
	"label-Z": require('./chit-label-z.png'),
	
	"label-II": require('./chit-label-II.png'),
	"label-III": require('./chit-label-III.png'),
	"label-IV": require('./chit-label-IV.png'),
	"label-VI": require('./chit-label-VI.png'),
	"label-VII": require('./chit-label-VII.png'),
	"label-VIII": require('./chit-label-VIII.png'),
	"label-IX": require('./chit-label-IX.png'),
	"label-XI": require('./chit-label-XI.png'),
	"label-XII": require('./chit-label-XII.png'),	
	
	//"French": require('./french_flag.jpg'),
	"French": require('./french.jpg'),
	"Austrian": require('./austrian_flag.png'),	

	"marengo": require("./marengo.jpg"),
	"antietam": require("./antietam.jpg"),
};
