module.exports = {
    TOAST: 'TOAST',
    SET_CURRENT: 'SET_CURRENT',
    SET_CUP: 'SET_CUP',
    SET_DELAY: 'SET_DELAY',
    SET_CHITS: 'SET_CHITS',
    ADD_CHIT: 'ADD_CHIT',
    REMOVE_CHIT: 'REMOVE_CHIT',
    ADD_CHIT_TO_POOL: 'ADD_CHIT_TO_POOL',
    REMOVE_CHIT_FROM_OPTIONAL: 'REMOVE_CHIT_FROM_OPTIONAL',
    PREV_TURN: 'PREV_TURN',
    NEXT_TURN: 'NEXT_TURN'
};
